### ISSUE TITLE
Add name of tracker to shared transactions

### ISSUE THREAD

**Issue by saifahn** [saifahn/expenseus#107]
## Overview

This would also involve adding a migration script for the existing database.

- [ ] Add name to back end code
- [ ] Create migration script
  - [ ] Test on dummy data, created by a script locally?
- [ ] Run on the real dynamodb

**Comment by saifahn** [comment]
One alternative is to fetch the list of trackers on the appropriate page and match it up using the ID instead. Would be much easier.
