### ISSUE TITLE
Add categories to expenses

### ISSUE THREAD

**Issue by saifahn** [saifahn/expenseus#33]
- [x]  Go through the types of expenses in the apps I currently have and note down the different categories.

Japanese

- [x] Osidori
- [x] Zaim
- ~~[ ] Tricount~~

English

- [x] Splitwise
- ~~[ ] Settle Up~~

---

- [ ] Make your own broad categories with sub-categories
- [ ] Think of how to represent these categories
- [ ] Add the new type struct to expenses
  - [ ] TDD?

**Comment by saifahn** [comment]
## Wordings from Splitwise

出費を追加する

ホーム

- 電気製品
- 家具
- 家庭用品
- メンテナンス
- その他
- 住宅ローン
- ペット
- 家賃

交通機関

- タクシー
- 自転車
- バス・電車
- 車
- ガス・燃料
- ホテル
- その他
- 駐車場
- 飛行機

公共料金

- クリーニング
- 電気
- 暖気・ガス
- その他
- ゴミ
- テレビ・電話・インターネット
- 水道

娯楽

- ゲーム
- 映画
- 音楽
- その他
- スポーツ

未分類

生活

- 養育関連
- 衣料品
- 教育関連
- ギフト
- 保険
- 医療費
- その他
- 税金

飲食

- 外食
- 食料品
- お酒
- その他

I think these are actually not very good, probably some amount of machine translation?

**Comment by saifahn** [comment]
## Zaim

かんたん入力

- 品目別に入力
- 金額
- 用途
- 詳細を入力
- 支払い元
- お店
  - お店名を入力
- メモ
  - メモを入力

支出選択

最近使った

一覧

食費

- 食料品
- カフェ
- 朝ごはん・昼ごはん・晩ごはん
- その他

内訳設定

日用雑貨

- 消耗品
- 子供関連
- ペット関連
- タバコ

交通

- 電車
- タクシー
- バス
- 飛行機

交際費

- 飲み会
- プレゼント
- ご礼儀・

エンタメ

- レジャー
- イベント
- 映画・動画
- 音楽
- 漫画
- 書籍
- ゲーム

教育・教養

- 習い事
- 新聞
- 参考書
- 受験料
- 学費
- 塾

美容・衣服

- 洋服
- アクセサリー・古物
- 下着
- ジム・健康
- 美容院
- コスメ
- エステ・ネイル
- クリーニング

医療・保険

- 病院代
- 薬代
- 生命保険
- 医療保険

通信

- 携帯電話料金
- インターネット関連費
- 放送サービス料
- 宅配便

水道・光熱

- 水道料金
- 電気料金
- ガス料金

住まい

- 家賃
- 住宅ローン返済
- 家具
- 家電
- リフォーム
- 住宅保険

クルマ

- ガソリン
- 駐車場
- 自動車保険
- 自動車税
- 自動車ローン
- 免許教習
- 高速料金

税金

- 年金
- 所得税
- 消費税
- 住民税

大型出費

- 旅行
- 住宅
- 自動車
- バイク
- 結婚
- 出産
- 介護
- 家具
- 家電

This was also surprisingly not as nice as I thought it would be. I'm going to look at OsidOri but I think after that I'm just going to figure out my own. And we can start with big categories first.

**Comment by saifahn** [comment]
## OsidOri

- 入力
- 支出
- 収入
- 振替
- 支払い担当
  - 家族
  - わたし
  - パートナー
- 支払い元
  - 現金
  - 新しく作成する
- お店のなまえ
- メモ
- 写真
- 未精算リストに入れる
- 収支の計算対象に入れる

食費

- 食料品
- 外食
- 朝ごはん・昼・晩
- カフェ
- 出前
- その他食費

日用品

- 生活雑貨
- 子供関連
- ペット関連
- タバコ

交通費

- 電車
- バス
- タクシー
- 飛行機

趣味・娯楽

- レジャー・スポーツ
- イベント
- 映画・動画
- 音楽・ゲーム・漫画
- 本
- 料金

衣服・美容

- アクセサリー・小物
- 下着
- 美容院・理髪
- 化粧品
- エステ・ネイル
- クリーニング

交際費

- 飲み会
- プレゼント
- 冠婚葬祭

健康・医療

- フィットネス
- マッサージ・整体
- 病院
- 薬代

教育・教養

- 書籍
- 新聞・雑誌
- 習い事
- 教科書・参考書
- 学費
- 塾

現金・カード

- カード引き落とし
- 電子マネーにチャージ
- カード返済
- ATM 引き出し

水道・光熱費

- 光熱費
- 電気代
- 水道代
- ガス代

通信費

- 携帯電話
- 固定電話
- インターネット
- 放送視聴料
- 情報サービス
- 宅配便・運送

住宅

- 家賃
- 住宅ローン
- 管理費・積立金
- 家具
- 家電
- リフォーム
- 地震・火災保険

車・バイク

- ガソリン
- 駐車場
- 道路料金
- 自動車ローン
- 自動車保険
- 自動車税
- 車検・整備

税・社会保障

- 所得税・住民税
- 年金
- 健康保険

保険

- 保険
- 生命保険
- 医療保険

特別な支出

- 特別な支出
- 家具・家電
- 住宅・リフォーム
- 結婚
- 妊活・出産
- 介護

資産形成

- 貯金
- iDeCo・企業型 DC
- NISA・積立 NISA
- 株式投資
- 投資信託
- 不動産投資
- 国債・社債

その他

未分類

I think these are mainly what I want to go with. We'll mainly only be using like 5 categories anyway haha.

**Comment by saifahn** [comment]
I think I will work on migrating to DynamoDB first so I don't have to duplicate the work of figuring out how to represent the data and implementing it.

Off the top of my head, I think my Redis would be something like:

- `categories` as a list of category IDs
- `category:id` contains the category name, the icon?
- `category:id:subcategory` contains the subcategory ids
- `subcategory:id` contains the subcategory name

### User stories

- As a user, when I enter an expense, I can choose a broad category for an expense to have quicker entry for when I don't care about the category too much.
- As a user, when I enter an expense, the default category is 未分類 so I can alter it later.
- As a user, I can choose a subcategory to have more granular analysis and control over my expenses.
  - For example, I might want to differentiate between water, gas, and electricity, but also see them together under 'utilities'

**Comment by saifahn** [comment]
Reading, reference for modelling the database:

- https://www.alexdebrie.com/posts/dynamodb-one-to-many/
- https://blog.theodo.com/2021/04/introduction-to-dynamo-db-modeling/
- https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-modeling-nosql-B.html

**Comment by saifahn** [comment]
Here's a list of categories I made:

| category.subcategory        | en_UK          | ja_JP            |
| --------------------------- | -------------- | ---------------- |
| food.food                   | Food           | 食費             |
| food.groceries              | Groceries      | 食料品           |
| food.eating-out             | Eating out     | 外食             |
| food.delivery               | Delivery       | 出前             |
| daily.daily                 | Daily goods    | 日用品           |
| daily.consumables           | Consumables    | 消耗品           |
| daily.children              | Child-related  | 子供関連         |
| transport.transport         | Transportation | 交通             |
| transport.train             | Train          | 電車             |
| transport.bus               | Bus            | バス             |
| transport.taxi              | Taxi           | タクシー         |
| utilities.utilities         | Utilities      | 水道・光熱・通信 |
| utilities.electricity       | Electricity    | 電気             |
| utilities.gas               | Gas            | ガス             |
| utilities.water             | Water          | 水道             |
| utilities.internet          | Internet       | インターネット   |
| utilities.phone             | Phone          | 携帯電話         |
| entertainment.entertainment | Entertainment  | エンタメ         |
| entertainment.leisure       | Leisure        | レジャー         |
| entertainment.hobbies       | Hobbies        | 趣味             |
| entertainment.music         | Music          | 音楽             |
| entertainment.film-video    | Film and video | 映画・動画       |
| entertainment.tv            | TV             | テレビ           |
| entertainment.subscriptions | Subscriptions  | 定期購読など     |
| clothing.clothing           | Clothing       | 衣料             |
| clothing.footwear           | Footwear       | 履き物           |
| beauty.beauty               | Beauty         | 美容             |
| beauty.cosmetics            | Cosmetics      | コスメ           |
| beauty.haircut              | Haircut        | ヘアカット       |
| travel.travel               | Travel         | 旅行             |
| travel.flights              | Flights        | 飛行機           |
| travel.accommodation        | Accommodation  | 宿泊             |
| home.home                   | Home           | ホーム           |
| home.electronics            | Electronics    | 電気製品         |
| home.furniture              | Furniture      | 家具             |
| home.kitchen                | Kitchen        | キッチン         |
| medical.medical             | Medical        | 医療             |
| unsorted.unsorted           | Unsorted       | 未分類           |
| other.other                 | Other          | その他           |
| social.social               | Social         | 交際費           |
| education.education         | Education      | 教育・教養       |
| education.lessons           | Lessons        | 習い事           |
| housing.housing             | Housing        | 住まい           |
| housing.rent                | Rent           | 家賃             |
| housing.mortgage            | Mortgage       | 住宅ローン       |
| car.car                     | Car            | 車               |
| insurance.insurance         | Insurance      | 保険             |

**Comment by saifahn** [comment]
## Tasks

- [ ] add category field to transactions
- [ ] add tests to make sure they work
- [ ] add category field to shared transactions
- [ ] add tests to make sure they work

Getting all expenses by category can be added in a separate PR.

Although, it needs to exist before that because of the index that is required for it.
