### ISSUE TITLE
Add amount to expenses

### ISSUE THREAD

**Issue by saifahn** [saifahn/expenseus#46]
This is like the most important part of the expenses!

**Comment by saifahn** [comment]
## To-dos

- [ ] Add to Transaction struct
- [ ] Make sure it works in tests
- [ ] Add a field to submit it in the front end
