### ISSUE TITLE
Delete personal transactions

### ISSUE THREAD

**Issue by saifahn** [saifahn/expenseus#67]
## UI

1. Press delete button
    - Accesible from card as well?
    - Otherwise, in the READ interface.
2. Confirm

## High level implementation

- Delete transaction at PK `USER#<user_id>`, SK `TRANSCTION#<transaction_id>`

**Comment by saifahn** [comment]
## Tasks

- [ ] add DeleteTransaction test to app
- [ ] add DeleteTransaction test to integration test
- [ ] add DeleteTransaction to ddb
- [ ] add button to delete transaction to frontend
