### ISSUE TITLE
Deploy front end to Vercel, back end as API that requests from vercel

### ISSUE THREAD

**Issue by saifahn** [saifahn/expenseus#90]
## Overview

- [x] https://expenses.saifahn.li as the next app on vercel
- ~~[ ] https://api.saifahn.li/expenses/v1/ on EC2~~
  - ended up with https://api-expenses.saifahn.li/api/v1 because it's simpler if I want to add more apis under my domain

## To-dos

- [x] environment variables for the CORS in local
- [x] then change the config for the EC2 instance
  - [x] stop the front end being served
  - [x] make `api` the right place
- [x] remove the front end serving stuff from repo
